In [10]:
import numpy as np
from matplotlib import pyplot as plt 
from scipy import linalg

In [2]:
# Gaussian 2
mu = np.array([0, 0])
# Eigendecomposition of the covariance matrix
eig_vals, eig_vecs = np.linalg.eig(np.array([[1,3], [3, 4]]))
cov = eig_vecs @ np.diag(np.array([2,4])) @ eig_vecs.T

In [5]:
print('Gaussian mean: ', mu)
print('Gaussian covariance:\n', cov)

Gaussian mean:  [0 0]
Gaussian covariance:
 [[2.5527864  0.89442719]
 [0.89442719 3.4472136 ]]


In [14]:
R = linalg.sqrtm(cov)
print('Matrix square-root:\n', R)
print('Check: R @ R - cov =\n', R @ R - cov)

Matrix square-root:
 [[1.57612095 0.26197166]
 [0.26197166 1.83809261]]
Check: R @ R - cov =
 [[1.33226763e-15 5.55111512e-16]
 [0.00000000e+00 8.88178420e-16]]


In [18]:
R @ np.linalg.inv(cov) @ R

array([[ 1.00000000e+00,  4.82788821e-17],
       [-1.14658732e-16,  1.00000000e+00]])

In [24]:
(np.array([[1,3,4]]).T @ np.array([[1,3,4]])).T

array([[ 1,  3,  4],
       [ 3,  9, 12],
       [ 4, 12, 16]])